{
 "title": "ebs-csi-driver",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "pvcname",
    "label": "Persistent Volume Claim",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info,  persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stat of << $pvcname >>", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pvcname" },
  {
   "title": "volume used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"$pvcname\"} * 100) / (kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"$pvcname\"})",
     "legendFormat": "{{persistentvolumeclaim}}-capacity-used"
    }
   ]
  },
  {
   "title": "Volume total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"$pvcname\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Inodes Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_inodes{persistentvolumeclaim=\"$pvcname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total-Available",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"$pvcname\"}",
     "legendFormat": "Total(Gb)"
    },
    {
     "expr": "kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"$pvcname\"}",
     "legendFormat": "Free(Gb)"
    }
   ]
  },
  {
   "title": "Volume free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"$pvcname\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Inodes Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_inodes_used{persistentvolumeclaim=\"$pvcname\"} * 100) / (kubelet_volume_stats_inodes{persistentvolumeclaim=\"$pvcname\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}