{
 "title": "Namespace Overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{pod=\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HPA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "barchart",
     "gridPos": { "h": 11, "w": 10, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_spec_max_replicas{namespace=\"$namespace\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"$namespace\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_min_replicas{namespace=\"$namespace\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HPA current_replicas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 104 },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"$namespace\"}",
       "legendFormat": "{{horizontalpodautoscaler}}"
      }
     ]
    },
    {
     "title": "HPA desired diff",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 10, "y": 151 },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_desired_replicas{namespace=\"$namespace\"} - kube_horizontalpodautoscaler_status_current_replicas{namespace=\"$namespace\"}",
       "legendFormat": "{{horizontalpodautoscaler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "StatefulSet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Count",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count by (created_by_name) (\n    kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\"}\n)",
       "legendFormat": "{{deployment_name}}"
      }
     ]
    },
    {
     "title": "Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 9, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  sum(\n      kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"} \n      * on(pod) group_left(created_by_name) \n      kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\"}\n  ) by (created_by_name)\n  / \n  sum(\n      kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\"}\n  ) by (created_by_name)\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "DaemonSet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Count",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 303 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count by (created_by_name) (\n    kube_pod_info{namespace=\"$namespace\",created_by_kind=\"DaemonSet\"}\n)",
       "legendFormat": "{{deployment_name}}"
      }
     ]
    },
    {
     "title": "Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 9, "y": 303 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  sum(\n      kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"} \n      * on(pod) group_left(created_by_name) \n      kube_pod_info{namespace=\"$namespace\",created_by_kind=\"DaemonSet\"}\n  ) by (created_by_name)\n  / \n  sum(\n      kube_pod_info{namespace=\"$namespace\",created_by_kind=\"DaemonSet\"}\n  ) by (created_by_name)\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "PVC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "PVC Usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"} - kubelet_volume_stats_used_bytes{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 * sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"} - kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}) / sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}[Capacity]"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}[Used]"
    }
   ]
  },
  {
   "title": "Deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Count",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": -16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count by (deployment_name) (\n  label_replace(\n    kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"},\n    \"deployment_name\",\n    \"$1\",\n    \"created_by_name\", \n    \"(.+)-[a-z0-9]+\"\n  )\n)",
       "legendFormat": "{{deployment_name}}"
      }
     ]
    },
    {
     "title": "Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 9, "y": -16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  sum(\n    label_replace(\n      kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"} \n      * on(pod) group_left(created_by_name) \n      kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"},\n      \"deployment_name\",\n      \"$1\",\n      \"created_by_name\", \n      \"(.+)-[a-z0-9]+\"\n    )\n  ) by (deployment_name)\n  / \n  sum(\n    label_replace(\n      kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"},\n      \"deployment_name\",\n      \"$1\",\n      \"created_by_name\", \n      \"(.+)-[a-z0-9]+\"\n    )\n  ) by (deployment_name)\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Memory * $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "pod",
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": -32 },
     "repeat": "container",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod=\"$pod\", container=\"$container\"}",
       "legendFormat": "Container: {{container}}"
      },
      {
       "expr": "kube_pod_container_resource_requests{pod=\"$pod\",container=\"$container\",resource=\"memory\"}",
       "legendFormat": "Request"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\"}) by (phase)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pods Count",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count by (created_by_kind, created_by_name) (\n    kube_pod_info{namespace=\"$namespace\"}\n)",
       "legendFormat": "{{created_by_kind}}> {{created_by_name}}"
      }
     ]
    },
    {
     "title": "Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  sum(\n      kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"} \n      * on(pod) group_left(created_by_kind, created_by_name) \n      kube_pod_info{namespace=\"$namespace\"}\n  ) by (created_by_kind, created_by_name)\n  / \n  sum(\n      kube_pod_info{namespace=\"$namespace\"}\n  ) by (created_by_kind, created_by_name)\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (vCore)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "sum(\n  (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\"}[5m])\n  * on(pod) group_left(created_by_name, created_by_kind) \n  kube_pod_info{namespace=\"$namespace\"})\n) by (created_by_name, created_by_kind)",
       "legendFormat": "{{created_by_kind}}> {{created_by_name}}"
      }
     ]
    },
    {
     "title": "(usage/request)%cpu",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\"}[5m])) by (pod) /\nsum(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"cpu\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum( \n(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\"} * on(pod, namespace) group_left(created_by_name,created_by_kind) kube_pod_info{namespace=\"$namespace\"})) by (created_by_name,created_by_kind)",
       "legendFormat": "{{created_by_kind}}> {{created_by_name}}"
      }
     ]
    },
    {
     "title": "(usage/request)%memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"POD\",container!=\"\"}) by (pod) /\nsum(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"memory\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod CPU * $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "pod",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (vCore)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": -9 },
     "repeat": "container",
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "sum (rate(container_cpu_usage_seconds_total{pod=\"$pod\", container=\"$container\"}[5m])) by (container)",
       "legendFormat": "Container: {{container}}"
      },
      {
       "expr": "sum (kube_pod_container_resource_requests{pod=\"$pod\",container=\"$container\",resource=\"cpu\"}) by (container)",
       "legendFormat": "Request"
      }
     ]
    }
   ]
  }
 ]
}